/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAuditLogsRouteImport } from './routes/_app.audit-logs'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppPartiesRouteImport } from './routes/_app.parties'
import { Route as AppPartsRouteImport } from './routes/_app.parts'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppUploadRouteImport } from './routes/_app.upload'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppDocumentsIndexRouteImport } from './routes/_app.documents.index'
import { Route as AppDocumentsDocumentIdRouteImport } from './routes/_app.documents.$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPartiesRoute = AppPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AppRoute,
} as any)
const AppPartsRoute = AppPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsDocumentIdRoute = AppDocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/parties': typeof AppPartiesRoute
  '/parts': typeof AppPartsRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/upload': typeof AppUploadRoute
  '/users': typeof AppUsersRoute
  '/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/documents/': typeof AppDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/dashboard': typeof AppDashboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/parties': typeof AppPartiesRoute
  '/parts': typeof AppPartsRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/upload': typeof AppUploadRoute
  '/users': typeof AppUsersRoute
  '/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/documents': typeof AppDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/parties': typeof AppPartiesRoute
  '/_app/parts': typeof AppPartsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/upload': typeof AppUploadRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/documents/$documentId': typeof AppDocumentsDocumentIdRoute
  '/_app/documents/': typeof AppDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit-logs'
    | '/dashboard'
    | '/notifications'
    | '/parties'
    | '/parts'
    | '/roles'
    | '/settings'
    | '/upload'
    | '/users'
    | '/documents/$documentId'
    | '/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit-logs'
    | '/dashboard'
    | '/notifications'
    | '/parties'
    | '/parts'
    | '/roles'
    | '/settings'
    | '/upload'
    | '/users'
    | '/documents/$documentId'
    | '/documents'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/audit-logs'
    | '/_app/dashboard'
    | '/_app/notifications'
    | '/_app/parties'
    | '/_app/parts'
    | '/_app/roles'
    | '/_app/settings'
    | '/_app/upload'
    | '/_app/users'
    | '/_app/documents/$documentId'
    | '/_app/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parties': {
      id: '/_app/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof AppPartiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parts': {
      id: '/_app/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof AppPartsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/': {
      id: '/_app/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/$documentId': {
      id: '/_app/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AppDocumentsDocumentIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPartiesRoute: typeof AppPartiesRoute
  AppPartsRoute: typeof AppPartsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUploadRoute: typeof AppUploadRoute
  AppUsersRoute: typeof AppUsersRoute
  AppDocumentsDocumentIdRoute: typeof AppDocumentsDocumentIdRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPartiesRoute: AppPartiesRoute,
  AppPartsRoute: AppPartsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUploadRoute: AppUploadRoute,
  AppUsersRoute: AppUsersRoute,
  AppDocumentsDocumentIdRoute: AppDocumentsDocumentIdRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
